CREATE SEQUENCE user_seq_gen MINVALUE 1
  START WITH 1
  INCREMENT BY 50;
CREATE SEQUENCE order_seq_gen MINVALUE 1
  START WITH 1
  INCREMENT BY 50;
CREATE SEQUENCE order_history_seq_gen MINVALUE 1
  START WITH 1
  INCREMENT BY 50;